#!/bin/bash

INPUTFILE=$1
PSFILE=$2

{
cat <<GnuplotScript
#cat <<EOF

set terminal pngcairo enhanced size 1000,600 background rgb 'white' font "Symbola,18" solid
set output "${PSFILE}"

# --- Log scales ---
set logscale x
set logscale y

# --- Labels ---
set xlabel "Injected h_{c}"
set ylabel "Recovered h_{c}"

# --- Grid and style ---
set grid
set key off
set border lw 1.5

# --- Ranges ---
set xrange [1e-12:1e-10]
set yrange [1e-12:1.2e-10]

set y2range [0:1]
set y2tics 0,0.2,1
set y2label "Fraction (h_{rec} > k{/Symbol s})"

set ytics nomirror
set y2tics

set grid xtics ytics mxtics mytics

# --- Ticks formatting ---
set format x "10^{%L}"
set format y "10^{%L}"

# --- Background color ---
#set object 1 rect from graph 0,0 to graph 1,1 fc rgb "#eaeaea" behind

# --- Ideal recovered=injected line ---
f(x)=x

g(x) = 0.5

#inj,N,median,low2sig,up2sig,q15,q85,err_median,snr_median,frac2,frac3
# --- Green quantile region ---
plot '${INPUTFILE}' using 1:4:5 with filledcurves fc rgb "#00cc00" fs solid 0.3 noborder, \
     '${INPUTFILE}' using 1:3:6:7 with yerrorbars pt 7 ps 0.6 lc rgb "red" lw 1, \
     f(x) with lines lw 2 lc rgb "black",\
     '${INPUTFILE}' using 1:10 axes x1y2 with linespoints pt 5 ps 0.8 lw 2 lc rgb "blue",\
     '${INPUTFILE}' using 1:11 axes x1y2 with linespoints pt 5 ps 0.8 lw 2 lc rgb "dark-green",\
     g(x) axes x1y2 with lines dt 2 lw 2 lc rgb "black"

GnuplotScript
} | gnuplot